export const CHILEAN_COMMUNES = [
  "Alhué",
  "Buin",
  "Calera de Tango",
  "Cerrillos",
  "Cerro Navia",
  "Colina",
  "Conchalí",
  "Curacaví",
  "El Bosque",
  "El Monte",
  "Estación Central",
  "Huechuraba",
  "Independencia",
  "Isla de Maipo",
  "La Cisterna",
  "La Florida",
  "La Granja",
  "La Pintana",
  "La Reina",
  "Lampa",
  "Las Condes",
  "Lo Barnechea",
  "Lo Espejo",
  "Lo Prado",
  "Macul",
  "Maipú",
  "María Pinto",
  "Melipilla",
  "Ñuñoa",
  "Padre Hurtado",
  "Paine",
  "Pedro Aguirre Cerda",
  "Peñaflor",
  "Peñalolén",
  "Pirque",
  "Providencia",
  "Pudahuel",
  "Puente Alto",
  "Quilicura",
  "Quinta Normal",
  "Recoleta",
  "Renca",
  "San Bernardo",
  "San Joaquín",
  "San José de Maipo",
  "San Miguel",
  "San Pedro",
  "San Ramón",
  "Santiago",
  "Talagante",
  "Tiltil",
  "Vitacura",
] as const;

export const DOG_BREEDS = [
  "Mestizo",
  "Akita",
  "American Staffordshire Terrier",
  "Beagle",
  "Border Collie",
  "Boxer",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Bull Terrier",
  "Cane Corso",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel",
  "Dachshund / Salchicha",
  "Dálmata",
  "Doberman",
  "Golden Retriever",
  "Gran Danés",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Maltés",
  "Pastor Alemán",
  "Pastor Australiano",
  "Pastor Belga Malinois",
  "Pinscher",
  "Pitbull",
  "Pomerania",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Samoyedo",
  "Schnauzer",
  "Shih Tzu",
  "Shar Pei",
  "Weimaraner",
  "Yorkshire Terrier",
  "Otra / No aparece",
] as const;
